from __future__ import annotations

import json
import shutil
import subprocess
from pathlib import Path

from .db import Database
from .exporter import subject_dir
from .util import utc_now


def build_codex_case(
    db: Database,
    vault: Path,
    subject_id: int,
    app_root: Path,
    browser_endpoint: str = "http://127.0.0.1:9222",
) -> Path:
    subject = db.get_subject(subject_id)
    if not subject:
        raise ValueError("Subject not found")
    case_root = app_root / "codex_cases" / subject["slug"]
    if case_root.exists():
        shutil.rmtree(case_root)
    case_root.mkdir(parents=True)

    source_root = subject_dir(vault, subject["slug"])
    summary = source_root / "Summary.md"
    if summary.exists():
        shutil.copy2(summary, case_root / "Summary.md")

    latest = db.latest_run(subject_id)
    if latest:
        latest_run_dir = Path(latest["run_dir"])
        if latest_run_dir.exists():
            destination = case_root / "latest_run"
            shutil.copytree(latest_run_dir, destination, dirs_exist_ok=True)

    context = {
        "generated_at": utc_now(),
        "subject": dict(subject),
        "profiles": [dict(row) for row in db.profiles_for_subject(subject_id)],
        "latest_results": [dict(row) for row in db.latest_results(subject_id)],
        "vault_subject_path": str(source_root),
        "browser_endpoint": browser_endpoint,
    }
    (case_root / "context.json").write_text(json.dumps(context, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    return case_root


def codex_prompt(
    case_root: Path,
    subject_name: str,
    browser_endpoint: str = "http://127.0.0.1:9222",
) -> str:
    return f"""You are assisting Contact Analyzer for subject {subject_name!r}.

Project rules:
- Read AGENTS.md first.
- The case bundle is at {case_root}.
- Inspect Summary.md, context.json, and latest_run diagnostics.
- The visible authenticated Chromium browser is available at {browser_endpoint}.
- Use the configured chrome-devtools MCP when browser inspection is necessary.
- The collector must physically open rendered profile relationship lists.
- Passive inspection of XHR/fetch responses generated by the visible browser is allowed; do not add official social-network API clients or API keys.
- Extract only canonical relationships: followers, following, and friends.
- Every contact must be a canonical profile URL and username when available.
- For a new platform, first run browser discovery, save the learned relationship controls, and add a conservative canonical profile URL rule.
- Never commit navigation, recommendations, posts, payment handles, or private-contact lists as contacts.
- Fix platform-specific selectors, count selectors, scrolling, pagination, network parsers, or discovery rules in contactanalyzer_app/adapters.py, collector.py, platform_catalog.py, or discovery.py.
- Do not delete or rewrite the user's vault data.
- Make the smallest targeted fix, run the test suite, and summarize exactly what changed.
"""


def run_codex(
    db: Database,
    vault: Path,
    subject_id: int,
    app_root: Path,
    non_interactive: bool = False,
    browser_endpoint: str = "http://127.0.0.1:9222",
) -> int:
    if not shutil.which("codex"):
        raise RuntimeError("codex is not available on PATH")
    subject = db.get_subject(subject_id)
    if not subject:
        raise ValueError("Subject not found")
    case_root = build_codex_case(
        db,
        vault,
        subject_id,
        app_root,
        browser_endpoint=browser_endpoint,
    )
    prompt = codex_prompt(case_root, subject["name"], browser_endpoint)
    if non_interactive:
        command = ["codex", "exec", "--sandbox", "workspace-write", prompt]
    else:
        command = ["codex", prompt]
    return subprocess.call(command, cwd=app_root)
